version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production

#  python-weather:
#    build:
#      context: .
#      dockerfile: Dockerfile.python
#    volumes:
#      - ./src:/app/src
#    environment:
#      - API_KEY=b46ba223dfe6adc962f8dc2c94ce7f2a
#    tty: true
